// FileBox Icons - Font Awesome icon class list
const iconList = [
    'fa-solid fa-folder','fa-regular fa-folder','fa-solid fa-folder-open','fa-regular fa-folder-open',
    'fa-solid fa-folder-plus','fa-solid fa-folder-minus','fa-solid fa-folder-tree',
    'fa-solid fa-file','fa-regular fa-file','fa-solid fa-file-lines','fa-regular fa-file-lines',
    'fa-solid fa-file-word','fa-solid fa-file-excel','fa-solid fa-file-powerpoint','fa-solid fa-file-pdf',
    'fa-solid fa-file-image','fa-solid fa-file-video','fa-solid fa-file-audio','fa-solid fa-file-code',
    'fa-solid fa-file-zipper','fa-solid fa-file-csv','fa-solid fa-file-pen','fa-solid fa-file-shield',
    'fa-solid fa-file-circle-check','fa-solid fa-file-circle-xmark','fa-solid fa-file-circle-plus',
    'fa-solid fa-file-arrow-up','fa-solid fa-file-arrow-down','fa-solid fa-file-import','fa-solid fa-file-export',
    'fa-solid fa-copy','fa-regular fa-copy','fa-solid fa-clipboard','fa-regular fa-clipboard',
    'fa-solid fa-scissors','fa-solid fa-paste','fa-solid fa-trash-can','fa-regular fa-trash-can',
    'fa-solid fa-pen','fa-solid fa-pen-to-square','fa-solid fa-pencil','fa-solid fa-eraser',
    'fa-solid fa-download','fa-solid fa-upload','fa-solid fa-share-nodes','fa-solid fa-link',
    'fa-solid fa-arrow-up-from-bracket','fa-solid fa-arrow-down-to-bracket',
    'fa-solid fa-magnifying-glass','fa-solid fa-magnifying-glass-plus','fa-solid fa-magnifying-glass-minus',
    'fa-solid fa-plus','fa-solid fa-minus','fa-solid fa-xmark','fa-solid fa-check',
    'fa-solid fa-circle-check','fa-solid fa-circle-plus','fa-solid fa-circle-minus','fa-solid fa-circle-xmark',
    'fa-solid fa-gear','fa-solid fa-gears','fa-solid fa-sliders',
    'fa-solid fa-ellipsis','fa-solid fa-bars','fa-solid fa-grip','fa-solid fa-table-cells',
    'fa-solid fa-list','fa-solid fa-list-check','fa-solid fa-list-ol',
    'fa-solid fa-rotate','fa-solid fa-arrows-rotate','fa-solid fa-arrow-rotate-left',
    'fa-solid fa-lock','fa-solid fa-lock-open','fa-solid fa-key','fa-solid fa-shield-halved',
    'fa-solid fa-eye','fa-regular fa-eye','fa-solid fa-eye-slash',
    'fa-solid fa-user','fa-regular fa-user','fa-solid fa-user-plus','fa-solid fa-user-gear',
    'fa-solid fa-users','fa-solid fa-user-group',
    'fa-solid fa-house','fa-solid fa-house-chimney','fa-solid fa-building','fa-solid fa-building-columns',
    'fa-solid fa-store','fa-solid fa-shop','fa-solid fa-cart-shopping','fa-solid fa-bag-shopping',
    'fa-solid fa-laptop','fa-solid fa-desktop','fa-solid fa-mobile-screen','fa-solid fa-tablet-screen-button',
    'fa-solid fa-display','fa-solid fa-server','fa-solid fa-hard-drive','fa-solid fa-database',
    'fa-solid fa-microchip','fa-solid fa-memory',
    'fa-solid fa-globe','fa-solid fa-earth-americas','fa-solid fa-earth-asia','fa-solid fa-earth-europe',
    'fa-solid fa-wifi','fa-solid fa-signal','fa-solid fa-bluetooth-b','fa-solid fa-usb',
    'fa-solid fa-battery-full','fa-solid fa-battery-half','fa-solid fa-battery-quarter',
    'fa-solid fa-power-off',
    'fa-solid fa-cloud','fa-solid fa-cloud-arrow-up','fa-solid fa-cloud-arrow-down',
    'fa-solid fa-sun','fa-solid fa-moon','fa-solid fa-cloud-sun','fa-solid fa-cloud-rain',
    'fa-solid fa-bolt','fa-solid fa-fire','fa-solid fa-snowflake',
    'fa-solid fa-code','fa-solid fa-terminal','fa-solid fa-laptop-code',
    'fa-solid fa-github','fa-brands fa-github','fa-brands fa-gitlab','fa-brands fa-gitee',
    'fa-solid fa-code-branch','fa-solid fa-code-commit','fa-solid fa-code-merge','fa-solid fa-code-pull-request',
    'fa-solid fa-chrome','fa-brands fa-chrome','fa-brands fa-firefox-browser','fa-brands fa-safari',
    'fa-solid fa-window-maximize','fa-solid fa-window-restore',
    'fa-solid fa-palette','fa-solid fa-paintbrush','fa-solid fa-pen-fancy','fa-solid fa-marker',
    'fa-solid fa-camera','fa-solid fa-camera-retro','fa-solid fa-image','fa-regular fa-image',
    'fa-solid fa-images','fa-regular fa-images','fa-solid fa-photo-film',
    'fa-solid fa-music','fa-solid fa-headphones','fa-solid fa-volume-high','fa-solid fa-volume-low',
    'fa-solid fa-microphone','fa-solid fa-microphone-slash',
    'fa-solid fa-video','fa-solid fa-film','fa-solid fa-clapperboard',
    'fa-solid fa-play','fa-solid fa-pause','fa-solid fa-stop','fa-solid fa-forward',
    'fa-solid fa-circle-play','fa-solid fa-circle-pause',
    'fa-solid fa-calendar','fa-regular fa-calendar','fa-solid fa-calendar-days','fa-solid fa-calendar-check',
    'fa-solid fa-clock','fa-regular fa-clock','fa-solid fa-stopwatch','fa-solid fa-hourglass-half',
    'fa-solid fa-bell','fa-regular fa-bell','fa-solid fa-envelope','fa-regular fa-envelope',
    'fa-solid fa-comment','fa-regular fa-comment','fa-solid fa-comments','fa-regular fa-comments',
    'fa-solid fa-message','fa-solid fa-inbox',
    'fa-solid fa-map-pin','fa-solid fa-location-dot','fa-solid fa-map','fa-solid fa-compass',
    'fa-solid fa-heart','fa-regular fa-heart','fa-solid fa-star','fa-regular fa-star',
    'fa-solid fa-bookmark','fa-regular fa-bookmark','fa-solid fa-flag','fa-regular fa-flag',
    'fa-solid fa-thumbs-up','fa-regular fa-thumbs-up','fa-solid fa-thumbs-down',
    'fa-solid fa-face-smile','fa-regular fa-face-smile','fa-solid fa-face-meh','fa-solid fa-face-frown',
    'fa-solid fa-trophy','fa-solid fa-medal','fa-solid fa-award','fa-solid fa-crown',
    'fa-solid fa-gift','fa-solid fa-gem','fa-solid fa-wand-magic-sparkles',
    'fa-solid fa-rocket','fa-solid fa-paper-plane','fa-solid fa-shuttle-space',
    'fa-solid fa-lightbulb','fa-regular fa-lightbulb',
    'fa-solid fa-wrench','fa-solid fa-screwdriver','fa-solid fa-hammer','fa-solid fa-toolbox',
    'fa-solid fa-print','fa-solid fa-fax',
    'fa-solid fa-book','fa-solid fa-book-open','fa-solid fa-graduation-cap',
    'fa-solid fa-flask','fa-solid fa-atom','fa-solid fa-dna',
    'fa-solid fa-chart-line','fa-solid fa-chart-bar','fa-solid fa-chart-pie','fa-solid fa-chart-column',
    'fa-solid fa-table','fa-solid fa-table-list',
    'fa-solid fa-money-bill','fa-solid fa-money-bill-wave','fa-solid fa-coins',
    'fa-solid fa-wallet','fa-solid fa-credit-card','fa-solid fa-receipt',
    'fa-solid fa-box','fa-solid fa-box-archive','fa-solid fa-boxes-stacked','fa-solid fa-cubes',
    'fa-solid fa-tags','fa-solid fa-tag','fa-solid fa-certificate','fa-solid fa-circle-info',
    'fa-solid fa-triangle-exclamation','fa-solid fa-circle-exclamation','fa-solid fa-shield',
    'fa-solid fa-leaf','fa-solid fa-seedling','fa-solid fa-tree',
    'fa-solid fa-gamepad','fa-solid fa-chess','fa-solid fa-puzzle-piece',
    'fa-solid fa-bicycle','fa-solid fa-car','fa-solid fa-bus','fa-solid fa-plane','fa-solid fa-ship','fa-solid fa-train',
    'fa-solid fa-mug-hot','fa-solid fa-utensils','fa-solid fa-pizza-slice',
    'fa-solid fa-briefcase','fa-solid fa-id-card','fa-solid fa-address-book',
    'fa-solid fa-sticky-note','fa-solid fa-note-sticky','fa-solid fa-thumbtack',
    'fa-solid fa-pen-ruler','fa-solid fa-ruler-combined',
    'fa-solid fa-filter','fa-solid fa-sort','fa-solid fa-arrow-up','fa-solid fa-arrow-down',
    'fa-solid fa-arrow-left','fa-solid fa-arrow-right',
    'fa-solid fa-expand','fa-solid fa-compress','fa-solid fa-maximize','fa-solid fa-minimize',
    'fa-solid fa-check-double','fa-solid fa-spell-check',
    'fa-solid fa-bug','fa-solid fa-spider','fa-solid fa-robot',
    'fa-solid fa-brain','fa-solid fa-hand','fa-solid fa-handshake',
    'fa-solid fa-droplet','fa-solid fa-fire-flame-curved',
    'fa-solid fa-sd-card','fa-solid fa-sim-card'
];
